/**
 * Curated seed of public US small-business websites for discovery/dry-run.
 * These are starting points for enrichment — contact emails are NEVER invented here.
 * Enrichment must extract only published mailto:/contact addresses from live pages.
 */

export type SeedBusiness = {
  businessName: string;
  website: string;
  city: string;
  state: string;
  category: string;
  tier: 1 | 2;
  /** Expected fit notes for scoring before enrich (optional hints only) */
  hints?: {
    repeatCustomer?: boolean;
    localSmall?: boolean;
  };
};

export const ACQUISITION_SEED_CATALOG: SeedBusiness[] = [
  {
    businessName: "Half Acre Beer Company",
    website: "https://halfacrebeer.com",
    city: "Chicago",
    state: "IL",
    category: "brewery",
    tier: 1,
    hints: { repeatCustomer: true, localSmall: true },
  },
  {
    businessName: "Revolution Brewing",
    website: "https://revbrew.com",
    city: "Chicago",
    state: "IL",
    category: "brewery",
    tier: 1,
    hints: { repeatCustomer: true, localSmall: true },
  },
  {
    businessName: "Goose Island Beer Co.",
    website: "https://www.gooseisland.com",
    city: "Chicago",
    state: "IL",
    category: "brewery",
    tier: 1,
    hints: { repeatCustomer: true, localSmall: true },
  },
  {
    businessName: "Louie Mueller BBQ",
    website: "https://www.louiemuellerbarbecue.com",
    city: "Taylor",
    state: "TX",
    category: "restaurant",
    tier: 1,
    hints: { repeatCustomer: true, localSmall: true },
  },
  {
    businessName: "Franklin Barbecue",
    website: "https://franklinbbq.com",
    city: "Austin",
    state: "TX",
    category: "restaurant",
    tier: 1,
    hints: { repeatCustomer: true, localSmall: true },
  },
  {
    businessName: "Joe's Kansas City Bar-B-Que",
    website: "https://www.joeskc.com",
    city: "Kansas City",
    state: "KS",
    category: "restaurant",
    tier: 1,
    hints: { repeatCustomer: true, localSmall: true },
  },
  {
    businessName: "Powell's City of Books",
    website: "https://www.powells.com",
    city: "Portland",
    state: "OR",
    category: "retail",
    tier: 1,
    hints: { repeatCustomer: true, localSmall: true },
  },
  {
    businessName: "City Lights Booksellers",
    website: "https://citylights.com",
    city: "San Francisco",
    state: "CA",
    category: "retail",
    tier: 1,
    hints: { repeatCustomer: true, localSmall: true },
  },
  {
    businessName: "Tartine Bakery",
    website: "https://tartinebakery.com",
    city: "San Francisco",
    state: "CA",
    category: "bakery",
    tier: 1,
    hints: { repeatCustomer: true, localSmall: true },
  },
  {
    businessName: "Magnolia Bakery",
    website: "https://www.magnoliabakery.com",
    city: "New York",
    state: "NY",
    category: "bakery",
    tier: 1,
    hints: { repeatCustomer: true, localSmall: true },
  },
  {
    businessName: "Intelligentsia Coffee",
    website: "https://www.intelligentsiacoffee.com",
    city: "Chicago",
    state: "IL",
    category: "cafe",
    tier: 1,
    hints: { repeatCustomer: true, localSmall: true },
  },
  {
    businessName: "Stumptown Coffee Roasters",
    website: "https://www.stumptowncoffee.com",
    city: "Portland",
    state: "OR",
    category: "cafe",
    tier: 1,
    hints: { repeatCustomer: true, localSmall: true },
  },
  {
    businessName: "Drybar",
    website: "https://www.drybar.com",
    city: "Los Angeles",
    state: "CA",
    category: "salon",
    tier: 1,
    hints: { repeatCustomer: true, localSmall: true },
  },
  {
    businessName: "Burke Williams Spa",
    website: "https://www.burkewilliamsspa.com",
    city: "Los Angeles",
    state: "CA",
    category: "spa",
    tier: 1,
    hints: { repeatCustomer: true, localSmall: true },
  },
  {
    businessName: "Equinox",
    website: "https://www.equinox.com",
    city: "New York",
    state: "NY",
    category: "fitness",
    tier: 1,
    hints: { repeatCustomer: true, localSmall: false },
  },
  {
    businessName: "Barry's",
    website: "https://www.barrys.com",
    city: "New York",
    state: "NY",
    category: "fitness",
    tier: 1,
    hints: { repeatCustomer: true, localSmall: true },
  },
  {
    businessName: "The Fillmore",
    website: "https://www.thefillmore.com",
    city: "San Francisco",
    state: "CA",
    category: "venue",
    tier: 1,
    hints: { repeatCustomer: true, localSmall: true },
  },
  {
    businessName: "First Avenue",
    website: "https://first-avenue.com",
    city: "Minneapolis",
    state: "MN",
    category: "venue",
    tier: 1,
    hints: { repeatCustomer: true, localSmall: true },
  },
  {
    businessName: "REI",
    website: "https://www.rei.com",
    city: "Seattle",
    state: "WA",
    category: "retail",
    tier: 2,
    hints: { repeatCustomer: true, localSmall: false },
  },
  {
    businessName: "Ace Hardware",
    website: "https://www.acehardware.com",
    city: "Oak Brook",
    state: "IL",
    category: "retail",
    tier: 2,
    hints: { repeatCustomer: true, localSmall: false },
  },
  {
    businessName: "PetSmart",
    website: "https://www.petsmart.com",
    city: "Phoenix",
    state: "AZ",
    category: "pet",
    tier: 2,
    hints: { repeatCustomer: true, localSmall: false },
  },
  {
    businessName: "Banfield Pet Hospital",
    website: "https://www.banfield.com",
    city: "Vancouver",
    state: "WA",
    category: "pet",
    tier: 2,
    hints: { repeatCustomer: true, localSmall: false },
  },
  {
    businessName: "Habitat for Humanity",
    website: "https://www.habitat.org",
    city: "Atlanta",
    state: "GA",
    category: "nonprofit",
    tier: 2,
    hints: { repeatCustomer: true, localSmall: false },
  },
  {
    businessName: "Local Motorsports Example Skip",
    website: "https://example.com",
    city: "Austin",
    state: "TX",
    category: "auto",
    tier: 2,
    hints: { repeatCustomer: false, localSmall: true },
  },
  {
    businessName: "Red Rock Canyon Visitor Center Shop",
    website: "https://www.redrockcanyonlv.org",
    city: "Las Vegas",
    state: "NV",
    category: "nonprofit",
    tier: 2,
    hints: { repeatCustomer: true, localSmall: true },
  },
  {
    businessName: "Pike Place Market",
    website: "https://www.pikeplacemarket.org",
    city: "Seattle",
    state: "WA",
    category: "retail",
    tier: 1,
    hints: { repeatCustomer: true, localSmall: true },
  },
  {
    businessName: "Reading Terminal Market",
    website: "https://readingterminalmarket.org",
    city: "Philadelphia",
    state: "PA",
    category: "retail",
    tier: 1,
    hints: { repeatCustomer: true, localSmall: true },
  },
  {
    businessName: "New Belgium Brewing",
    website: "https://www.newbelgium.com",
    city: "Fort Collins",
    state: "CO",
    category: "brewery",
    tier: 1,
    hints: { repeatCustomer: true, localSmall: true },
  },
  {
    businessName: "Deschutes Brewery",
    website: "https://www.deschutesbrewery.com",
    city: "Bend",
    state: "OR",
    category: "brewery",
    tier: 1,
    hints: { repeatCustomer: true, localSmall: true },
  },
  {
    businessName: "Russian River Brewing Company",
    website: "https://russianriverbrewing.com",
    city: "Santa Rosa",
    state: "CA",
    category: "brewery",
    tier: 1,
    hints: { repeatCustomer: true, localSmall: true },
  },
];
