import type { MetadataRoute } from "next";
import { appUrl } from "@/lib/utils";

export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      {
        userAgent: "*",
        allow: [
          "/",
          "/pricing",
          "/features",
          "/deliverability",
          "/templates",
          "/migrate",
          "/security",
          "/status",
          "/integrations",
          "/email-marketing-guide",
          "/resources",
          "/changelog",
          "/cheap-email-marketing",
          "/email-marketing-cost",
          "/email-newsletter-software",
          "/small-business-newsletter-software",
          "/email-marketing-without-gmail",
          "/about",
          "/how-sendfable-works",
          "/mailchimp-alternative",
          "/mailerlite-alternative",
          "/constant-contact-alternative",
          "/guides/",
          "/best-email-marketing-software",
          "/alternatives/",
          "/compare/",
          "/solutions/",
          "/email-marketing-for-small-business",
          "/vs/",
          "/partners",
          "/terms",
          "/privacy",
          "/acceptable-use",
          "/refund-policy",
          "/contact",
          "/feed.xml",
          "/f/",
        ],
        disallow: [
          "/dashboard",
          "/campaigns",
          "/contacts",
          "/segments",
          "/tags",
          "/forms",
          "/billing",
          "/settings",
          "/onboarding",
          "/admin",
          "/inbox",
          "/library",
          "/api/",
          "/unsubscribe/",
          "/invite/",
          "/login",
          "/signup",
          "/early-access",
          "/link-unavailable",
          "/sms/",
        ],
      },
    ],
    sitemap: appUrl("/sitemap.xml"),
  };
}
